### ISSUE TITLE
请问你的站内搜索是怎么做的

### ISSUE THREAD

**Issue by ACBingo** [MOxFIVE/hexo-theme-yelee#10]
RT

**Comment by MOxFIVE** [comment]
百度站内搜索，嵌入式搜索结果。
http://zn.baidu.com/cse/wiki/index?id=356&category_id=17#h2_link_17_6

**Comment by netcan** [comment]
我这有个方案：http://www.netcan.xyz/2015/11/20/%E5%AE%8C%E7%BE%8E%E8%A7%A3%E5%86%B3Hexo%E9%9D%99%E6%80%81%E5%8D%9A%E5%AE%A2%E6%90%9C%E7%B4%A2%E9%97%AE%E9%A2%98/
