### ISSUE TITLE
最新修改的文章如何显示到博客最前面

### ISSUE THREAD

**Issue by jp1017** [MOxFIVE/hexo-theme-yelee#104]
最新修改的文章如何显示到博客最前面呢？

默认是根据创建时间，该如何修改下？

**Comment by MOxFIVE** [comment]
置顶：http://www.netcan666.com/2015/11/22/解决Hexo置顶问题/
按更新时间排序：改一下上面文章里的代码 `a.date`, `b.date` 分别改为 `a.updated`, `b.updated`

**Comment by jp1017** [comment]
@MOxFIVE 完美解决，非常感谢 :+1: :smile:

**Comment by stevenjoezhang** [comment]
Hexo 已实现文章置顶参数： hexojs/hexo-generator-index#51
