### ISSUE TITLE
图标小问题

### ISSUE THREAD

**Issue by RanchoCooper** [MOxFIVE/hexo-theme-yelee#107]
文章右侧的三个按钮(顶部,底部,查看评论)
以及评论上方的一排分享图标
chrome不能正常显示, 但手机和firefox正常

**Comment by MOxFIVE** [comment]
不清楚，我用 Chrome 打开你的网站图标显示正常

**Comment by AsanZhang** [comment]
@RanchoCooper 清空下浏览器的缓存试试看。

**Comment by RanchoCooper** [comment]
哦哦, 是我的chrome插件stylish影响了css...
