### ISSUE TITLE
考虑做一个社交链接的自定义方案吗？

### ISSUE THREAD

**Issue by Arondight** [MOxFIVE/hexo-theme-yelee#108]
参见 fae16d0f816fa4f170e7ac9ad86bd07db936370d #34 

现在的情况是想添加一些其他的社交链接，但是按照现有的机制，必须手动改代码，而无法全部在配置文件中完成。这样带来一个非常麻烦的问题：更新主题的时候需要手动处理冲突。

不知道有没有兴趣做成一个链接、图标等都可以在配置文件中指定的机制，一个不错的例子是[hexo-theme-freemind](https://github.com/wzpan/hexo-theme-freemind/blob/58782111026ae770f57b3ae40adb8e524ffcba86/_config.yml#L24-L36)

**Comment by MOxFIVE** [comment]
你提到的方案是主题 3.0 版本前的，现在要新增图片或字体图标话，加几个词就差不多了，冲突应该很少。https://github.com/MOxFIVE/hexo-theme-yelee/commit/41beb86dd348c659bec430339842561f74e16d28

另外也可以直接在这申请添加新社交图标，我会整合进主题中

至于自定义图标，涉及的变量有点多（类型、链接、颜色和大小等），放配置中感觉略臃肿，暂不考虑
