### ISSUE TITLE
Add comment count  首页文章显示评论数量

### ISSUE THREAD

**Issue by Arondight** [MOxFIVE/hexo-theme-yelee#109]
参见 cc7eff47d0368f94fc9541d9d70154be500e8b6d

看到这个提交里是可以做到的，不知道首页有没有可能加上这个功能呢？

**Comment by MOxFIVE** [comment]
可以，以后会加上

**Comment by ydx1013** [comment]
能不能在电脑上也添加像ipad上面的css配色选项呢，个人觉得ipad版的太美了。嘿嘿

**Comment by MOxFIVE** [comment]
@ydx1013 那是为移动端定制的随机纯色背景，在电脑上的效果应该还需要调整，以后会提供配置

现在要在电脑上用的话，改一行代码就行 [background.ejs#L5](https://github.com/MOxFIVE/hexo-theme-yelee/blob/v3.5/layout/_partial/background.ejs#L5)

```diff
- if (iPad > -1 || $(".left-col").css("display") === "none") {
+ if (1) {
```

**Comment by ydx1013** [comment]
已经修改了。依然好看，谢谢。

**Comment by MOxFIVE** [comment]
#### DEMO: http://moxfive.xyz/

> 启用设置后在主页显示文章评论数，点击进入对应评论区（多说 或者 Disqus）

![snip20160627_5](https://cloud.githubusercontent.com/assets/10032927/16363510/0222db14-3bff-11e6-9bba-fa858921dc64.png)
