### ISSUE TITLE
yilia主题动态加载

### ISSUE THREAD

**Issue by ydx1013** [MOxFIVE/hexo-theme-yelee#110]
你好，我用的yilia主题，按照您的修改记录修改，为什么preload_comment: true的时候直接显示评论框，preload_comment: false的时候显示点击加载的按钮，但是点击没有反应呢？

不是我修改错误的原因，我按照你的记录修改了6遍都是这个样子。

**Comment by MOxFIVE** [comment]
看不到你改动后的样子，感觉上是没关联到点击事件或者事件未生效

> 事件未生效的原因可能是没匹配到评论条，其他原因请自行排查
```diff
- <div class="duoshuo">
+ <div class="duoshuo" id="comments">
```

> [click2show.ejs](https://github.com/MOxFIVE/hexo-theme-yelee/blob/master/layout/_partial/comments/click2show.ejs)
```js
var $commentBar = $("#comments aside.comment-bar");
```
