### ISSUE TITLE
如何添加tiddlywiki到这个主题下呢？

### ISSUE THREAD

**Issue by AverageJoeWang** [MOxFIVE/hexo-theme-yelee#111]
看到作者有添加tiddlywiki，所以也想添加一个wiki管理。

**Comment by MOxFIVE** [comment]
把文件保存为 `yelee/source/wiki/index.html` ，部署后通过访问地址为 `http://域名/wiki/`

http://www.tiddlywiki.cn/

---
现在我主要用 Gist 管理 wiki ，因为代码片段比较多

**Comment by AverageJoeWang** [comment]
恩，十分感谢。也是，代码多的还是有高亮的看起来不错。十分感谢作者！
