### ISSUE TITLE
首页的文章 tag跟分类无法区分

### ISSUE THREAD

**Issue by lengthmin** [MOxFIVE/hexo-theme-yelee#116]
http://litten.github.io/
yilia主题是有个tag的图片的
http://moxfive.xyz/
http://lengthmin.com/
yelee主题区分不了  tag跟分类

**Comment by MOxFIVE** [comment]
不大明白，为什么不能区分
![snip20160629_1](https://cloud.githubusercontent.com/assets/10032927/16455380/aa7cb200-3e46-11e6-9dc5-d067442990f1.png)

**Comment by lengthmin** [comment]
@MOxFIVE  对不起呀，我忘记说移动端了。移动端是看不到这个书跟标签的图片的

**Comment by MOxFIVE** [comment]
把下面几行代码删掉就会显示了
[/source/css/_partial/mobile.styl#L190](https://github.com/MOxFIVE/hexo-theme-yelee/blob/v3.5/source/css/_partial/mobile.styl#L190)

```stylus
.article-category::before{
    display: none;
}
.article-tag::before {
     display: none;
}
```
