### ISSUE TITLE
分级标题和文章目录

### ISSUE THREAD

**Issue by RanchoCooper** [MOxFIVE/hexo-theme-yelee#119]
为了标题有更直观的区别, 我经常会像下面这样用

```
# first

### seconde
```

这样分级 `3.5` 出来的目录就是

```
1. first
    1.0.1 seconde
```

**Comment by MOxFIVE** [comment]
不清楚，我用 3.0 和 2.5 版本测试也是这么显示

你可以直接改 H2 标题样式 [heading.styl](https://github.com/MOxFIVE/hexo-theme-yelee/blob/v3.5/source/css/_partial/customise/heading.styl)，然后文档这么写

``` markdown
## first

### seconde
```
