### ISSUE TITLE
网站计数与数据重置问题

### ISSUE THREAD

**Issue by tsstss123** [MOxFIVE/hexo-theme-yelee#12]
访问好奇访问次数是怎么统计的...怎么手动重置呢?

**Comment by MOxFIVE** [comment]
统计借助了不蒜子服务：http://ibruce.info/2015/04/04/busuanzi/
目前还不能重置数据，等作者更新。
另外 `hexo s` 本地统计与 在线网站上的统计互不相干，所以一般也不需要重置。
