### ISSUE TITLE
同一站点下，不同页面下，百度share有的抓取不到js？

### ISSUE THREAD

**Issue by muxiaobai** [MOxFIVE/hexo-theme-yelee#120]
![2016](https://cloud.githubusercontent.com/assets/13265901/16557945/3323588a-4215-11e6-8b39-3266bc446208.PNG)
![20162](https://cloud.githubusercontent.com/assets/13265901/16557946/3324e632-4215-11e6-83ee-c82a5e7988c6.PNG)

**Comment by muxiaobai** [comment]
分析了一下，chrome下，有https的情况下，抓取不到js，没有https的时候，可以抓取。
![1](https://cloud.githubusercontent.com/assets/13265901/16558012/9d641aa4-4215-11e6-9ecd-fab6198d0b11.PNG)
![2](https://cloud.githubusercontent.com/assets/13265901/16558013/9d732602-4215-11e6-9039-ffafbe1cc028.PNG)

**Comment by MOxFIVE** [comment]
百度分享现在还不支持 HTTPS，建议使用 [AddThis](http://moxfive.coding.me/yelee/5.Vendor/addthis.html) 替代
