### ISSUE TITLE
目录的默认分级level

### ISSUE THREAD

**Issue by RanchoCooper** [MOxFIVE/hexo-theme-yelee#122]
问下怎么设置文章左侧目录的默认分级

比如有的文章很长, 父标题下面有很多的子标题

这样一来目录就被叶子标题给霸占了, 

文章的整体脉络不能一目了然

我的想法是, # 有四级标题

那比方设置了dir_level为2

那么生成的目录里面

就只展开到 ##

而其他的自动折叠起来

**Comment by MOxFIVE** [comment]
更新主题，设置下目录最大级数，默认 3 ，也就是 `### h3` 之后的标题都不会在目录中显示

https://github.com/MOxFIVE/hexo-theme-yelee/commit/659f6eabe4922699a69bc583404c9f778b896535
