### ISSUE TITLE
请问在哪更改授权信息?

### ISSUE THREAD

**Issue by WhisperKarl** [MOxFIVE/hexo-theme-yelee#124]
请问去哪文章末尾的授权信息?把文章地址改为自己的地址.
还有为啥本地能显示评论模块,同步到github上在线环境看不到评论模块呢?

**Comment by MOxFIVE** [comment]
[文末原文链接设置](http://moxfive.coding.me/yelee/4.Page-Setup/copyright.info.html#原始链接设置)

友言 HTTPS 下似乎无法正常使用
http://moxfive.coding.me/yelee/1.Getting-Started/https.html
