### ISSUE TITLE
关于nav.ejs与_config.yml 对自动更新产生冲突的问题

### ISSUE THREAD

**Issue by huangjj27** [MOxFIVE/hexo-theme-yelee#126]
因为nav.ejs（文章版本）与_config.yml带有个性化的设置的信息，每次更新的时候都会提醒我先做一个commit以解决冲突，比较不方便，所以想问一下作者这两个文件是否已经足够完善而可以在以后获取更新的时候进行忽略更新？

**Comment by MOxFIVE** [comment]
是的，可以忽略。真有必要的改动我会在这个主题里提醒你的
