### ISSUE TITLE
关于fancybox图片浏览器的疑问

### ISSUE THREAD

**Issue by hechenzhe** [MOxFIVE/hexo-theme-yelee#127]
之前在CSDN博客发表文章，使用了CSDN的图片链接，如下：
![示例图片](http://img.blog.csdn.net/20160612153202242)
但是开启了fancybox功能后，点击该图片会直接跳至该图片链接，并没有应有的弹出显示效果

问是否图片必须位于本地才有效果？

**Comment by hechenzhe** [comment]
[文章所在地址](http://www.manso-he.net/2016/07/19/Android%20Sensor%E6%A1%86%E6%9E%B6%E7%AE%80%E8%BF%B0%EF%BC%88%E4%B8%80%EF%BC%89/)<----点我

**Comment by MOxFIVE** [comment]
图片链接没有后缀名，识别有些问题，已修复。更新主题或者参考上面 commit 微调就行

**Comment by hechenzhe** [comment]
辛苦了
