### ISSUE TITLE
How to handle 404 page

### ISSUE THREAD

**Issue by riapp** [MOxFIVE/hexo-theme-yelee#14]
I setup the 404 page according with the manual
8. 404 Page:
```
hexo new page 404
```
And then set `permalink: /404` in `/source/404/index.md` front matter.

But when I typing http://0.0.0.0:4000/not-existed-page the 404 page is not getting displayed.

![image](https://cloud.githubusercontent.com/assets/1283734/11898202/39866f86-a5ea-11e5-9efe-5ea91116ce71.png)

Is there any sort fallback should be made in the source files ?

**Comment by MOxFIVE** [comment]
In order to make not existed link redirect to 404 page, you should deploy your site to your servers (GitHub Pages or other host).  
Take my blog as an example.  http://moxfive.xyz/not-existed-page

If you want to see 404 page in localhost, type: http://0.0.0.0:4000//404.html
