### ISSUE TITLE
希望能添加Telegram社交信息展示

### ISSUE THREAD

**Issue by ilovesusu** [MOxFIVE/hexo-theme-yelee#140]
> 有个需求,希望能在主页现实Telegram的图标和_config.yml中subnav:有telegram子项

**Comment by lengthmin** [comment]
这个很简单的。。
在subnav中添加```Telegram: ""```字段
在theme/yelee/source/img/中放一张telegram的图片
![Telegram.png](https://ooo.0o0.ooo/2016/08/28/57c2645de8e7c.png)
修改source/css/_partial/customise/social-icon.styl，在25行左右修改img-logo的内容，找一行添加```Telegram white 90```
就ok了。
效果图:
![Screenshot_2016-08-28-12-15-42-57.png](https://ooo.0o0.ooo/2016/08/28/57c26591d3ab5.png)

**Comment by lengthmin** [comment]
图挂了。。
[Screenshot_2016-08-28-12-15-42-57.png](https://ooo.0o0.ooo/2016/08/28/57c26591d3ab5.png)

[Telegram.png](https://ooo.0o0.ooo/2016/08/28/57c2645de8e7c.png)

**Comment by ilovesusu** [comment]
多谢
