### ISSUE TITLE
如何修改文末版权信息

### ISSUE THREAD

**Issue by d2Code** [MOxFIVE/hexo-theme-yelee#147]
在文末版权信息中，许可协议一栏中的声明是 **转载请保留原文连接及作者**，如何修改这个声明？

**Comment by MOxFIVE** [comment]
https://github.com/MOxFIVE/hexo-theme-yelee/blob/master/languages/default.yml#L29
https://github.com/MOxFIVE/hexo-theme-yelee/blob/master/languages/zh-Hans.yml#L29

改完后执行 `hexo clean && hexo s` 预览
