### ISSUE TITLE
firefox浏览器下左菜单栏偏移

### ISSUE THREAD

**Issue by Leefir** [MOxFIVE/hexo-theme-yelee#148]
firefox49.0.0.6103
![firefox](https://cloud.githubusercontent.com/assets/20868617/18747182/6ede0668-80fe-11e6-9489-032a25e71b31.png)
![chrome](https://cloud.githubusercontent.com/assets/20868617/18747181/6ec6ca66-80fe-11e6-9a59-586368968c68.png)

**Comment by cloisonne** [comment]
I have met the same issue. The latest Firefox running in Ubuntu 16.04.

**Comment by cloisonne** [comment]
https://github.com/MOxFIVE/hexo-theme-yelee/pull/151     @Leefir

**Comment by Leefir** [comment]
Thank you! @cloisonne. I have managed to fix it with the help of your commit!
