### ISSUE TITLE
代码区等宽字体

### ISSUE THREAD

**Issue by zqhxuyuan** [MOxFIVE/hexo-theme-yelee#16]
这是原始的md:
```
      30min ago              10min ago          now
---------|----------------------|----------------|---->
         |<-------------------->|
```

在主题中显示的是:
![4space](http://img.blog.csdn.net/20151224213436504)

看起来并不是很美观. 这个问题应该是用了两个空格了吧.   换成4个空格, 应该会好点. 
还有-横杆这个字符貌似变短了. 导致上面的|(竖杆)对应的字没对应上. 这个是什么字体大小的问题吗?

**Comment by MOxFIVE** [comment]
![snip20151224_1](https://cloud.githubusercontent.com/assets/10032927/11995606/7d590dba-aa8e-11e5-966e-9bee0b62c717.png)

代码框的字体我后来调整过了，你可以手动修改一下。https://github.com/MOxFIVE/hexo-theme-yelee/commit/bba4e34f1daa3bf8379aa6f6ca5d02808114964b

[highlight.styl#L33](https://github.com/MOxFIVE/hexo-theme-yelee/blob/bba4e34f1daa3bf8379aa6f6ca5d02808114964b/source/css/_partial/highlight.styl#L33)

``` diff
.article-entry
  pre, code
+   font-family: Menlo, Consolas, "Source Code Pro", Inconsolata, Monaco, monospace, "Microsoft YaHei", "Hiragino Sans GB", "WenQuanYi Micro Hei", sans-serif
    font-size: 1em
```

**Comment by zqhxuyuan** [comment]
Tks!
