### ISSUE TITLE
favicon该如何添加？

### ISSUE THREAD

**Issue by sarazhang123** [MOxFIVE/hexo-theme-yelee#17]
我在theme配置文件中添加了如下代码：
```
favicon: http://7xpg8c.com1.z0.glb.clouddn.com/8096659.png
```
但是最终生成的public文件夹中依旧没有favicon.png
必须自己在public文件夹中添加favicon吗？这样每次`hexo g`后该icon就被删掉了。

**Comment by MOxFIVE** [comment]
写法问题。内容含有英文冒号时要加引号，下面两种写法都可以：
```
favicon: "http://7xpg8c.com1.z0.glb.clouddn.com/8096659.png"

favicon: //7xpg8c.com1.z0.glb.clouddn.com/8096659.png
```

**Comment by sarazhang123** [comment]
为什么我试了一下依旧没有看到favicon.png？确定没问题吗？
头像的写法如下
```
avatar: http://7xpg8c.com1.z0.glb.clouddn.com/ember.jpg
```
是可以work的

**Comment by sarazhang123** [comment]
原来网站图标不是根据站点下的favicon.png来的，而是
```
<link rel="icon" href="http://7xpg8c.com1.z0.glb.clouddn.com/8096659.png">
```
我之前的写法也是可以的，只是我一直在寻找favicon.png而忽略了实际效果

**Comment by MOxFIVE** [comment]
那奇怪了，小图标我设置 favicon 就行。上面的代码和配置，看上去是一样的。
图片你不是放在 source 文件夹，确实不会生成到 public 文件夹中。
