### ISSUE TITLE
多说评论系统不能用啊

### ISSUE THREAD

**Issue by Jatstar** [MOxFIVE/hexo-theme-yelee#19]
duoshuo: 
  on: true
  domain: http://jatgit.duoshuo.com
  # 是否开启多说评论，http://duoshuo.com/create-site/
  # 使用上面网址登陆你的多说，然后创建站点，在 domain 中填入你设定的域名
  # http://你的多说域名.duoshuo.com

~~~不出来么

**Comment by MOxFIVE** [comment]
```
domain: jatgit
```
这样填就行了，不用全写。
