### ISSUE TITLE
怎么修改copyright？

### ISSUE THREAD

**Issue by hubojing** [MOxFIVE/hexo-theme-yelee#193]
比如去掉更新时间。
另外，如何实现统计文章字数的功能？

谢谢。

**Comment by zhwhong** [comment]
在 **layout/_partial/post/nav.ejs** 里面修改，这个是控制copyright的。

统计整个博客所有文章字数可以使用： <%= totalcount(site) %>

统计某一篇文章字数使用：<%= wordcount(post.content) %>，可以看[这里](https://github.com/Hzwcode/Hzwcode.github.io/blob/blog-source/themes/yelee/layout/_partial/post/word.ejs)

效果见我的博客： http://zhwhong.ml

**Comment by zhwhong** [comment]
可以在copyright里面增加文章版本控制（方便查看文章修改历史）和markdown原文下载等功能

**Comment by hubojing** [comment]
非常感谢。

**Comment by zhwhong** [comment]
没事，不谢～
