### ISSUE TITLE
底部单篇文章浏览数不显示

### ISSUE THREAD

**Issue by hubojing** [MOxFIVE/hexo-theme-yelee#194]
底部单篇文章浏览数不显示。

是哪里的问题？怎么解决？谢谢。

**Comment by zhwhong** [comment]
这个不是主题的问题，应该是 ‘不蒜子’ 插件后台的问题，我曾经也遇到过，一般过几个小时就好了，不用管，不影响文章浏览数统计。如果觉得不爽也可以考虑使用 LeanCloud 来统计文章浏览数。

**Comment by hubojing** [comment]
我感觉不是的，因为它从来没有显示过。估计是代码出了问题，但我不知道是哪里出了问题。。。

**Comment by zhwhong** [comment]
你是不是文章页面中除了最底部，还有其他哪里调用过“不蒜子”的  **busuanzi_container_page_pv** 单篇文章阅读量统计功能，我记得之前遇到过。这个变量在单次加载时如果前面获取过一次，第二个地方再获取好像就取不到它的值了。就我的感觉，好像只能调用一次，如果要调用多次，需要另外弄变量保存那个page_pv的值。
你检查一下你是不是文章中还有其他地方调用过阅读量统计。
我的反正底部显示是正常的。

http://zhwhong.ml

**Comment by hubojing** [comment]
问题解决了，确实是这个原因，非常感谢！
