### ISSUE TITLE
关于站内搜索

### ISSUE THREAD

**Issue by Gabrielkaliboy** [MOxFIVE/hexo-theme-yelee#195]
本地搜索，设置好了以后，网页打开，一直是no result find ,我看了一下你的，并没有这个情况，尝试将onload改为false，当激活搜索框时再下载索引数据 [按需加载]，你的文档里里面这么写的，还是没有生效，如果可以，麻烦回复一下

**Comment by zhwhong** [comment]
这个站内搜索按理说应该只要安装了 hexo-generator-search 插件，应该就可以搜到东西了。不管onload是false还是true。你搜不到要么是你网速的问题，点了之后等一下试试，要么可能是你输入的字符太短，如果只输入一个字符一般不会检索的。还有你可以看一下你生成的目录下的search.xml是不是正确的格式，比如类似于这样： https://github.com/zhwhong/zhwhong.github.io/blob/master/search.xml ， 你在你自己的search.xml这个页面使用ctrl+F搜索你之前搜过的关键字再试试。如果格式正常，能搜到，那就不是插件的问题了，如果这里本来就没有，可能就是插件的问题了

**Comment by Durant35** [comment]
+ 可能是因为这个的缘故
![image](https://cloud.githubusercontent.com/assets/6770853/26751704/5fbc51ee-4872-11e7-87fb-370cf52b578b.png)
不使用用这个功能，好像就能正常使用了。给博主赞一个！！

**Comment by Gabrielkaliboy** [comment]
多谢二位帮忙

**Comment by Durant35** [comment]
@Gabrielkaliboy 请问下是如何解决的呀？我的这个功能现在好像会时不时出现异常
