### ISSUE TITLE
关于基础设置里面的文章摘要，请再详细说明一下

### ISSUE THREAD

**Issue by Gabrielkaliboy** [MOxFIVE/hexo-theme-yelee#196]
作者给的两种设置方式，没有看懂，方法一和方法二是吧这个代码放在了什么位置?主题的文件配置里面吗?

**Comment by Gabrielkaliboy** [comment]
已解决，是放在md文档里面。

**Comment by zhwhong** [comment]
要么在md文件里加  \<!--more--\> ，之前的部分会自动显示在摘要里，要么在.md文件题头使用 description: XXXXX 标签添加描述
