### ISSUE TITLE
首页文章预览行数如何控制

### ISSUE THREAD

**Issue by icyfox-bupt** [MOxFIVE/hexo-theme-yelee#2]
你好，看到你demo页面里的文章预览只有5、6行
git下来后的主题在预览时会显示很多
怎么控制？

@MOxFIVE

**Comment by beyondskyway** [comment]
@icyfox-bupt 文章里面加，下面的部分会被隐藏

**Comment by icyfox-bupt** [comment]
成了，前端程序员赛高~
