### ISSUE TITLE
你们都是使用的什么评论插件？貌似yelee的插件不好使

### ISSUE THREAD

**Issue by Gabrielkaliboy** [MOxFIVE/hexo-theme-yelee#202]
谁布置过啊，求个帮助。

**Comment by FernandoZhuang** [comment]
现在使用的是网易云跟帖，本人博客是0xshare.me @Gabrielkaliboy 
内附相关博客阅读，欢迎追问

**Comment by FernandoZhuang** [comment]
@Gabrielkaliboy 使用的是网易云跟帖，[参考文章](https://txisfine.cn/2017/05/08/yelee-wangyiyun-gentie.html)
另外本人写了一份涉及[跟帖的文章](http://0xshare.me/)，欢迎辅助参考

**Comment by Gabrielkaliboy** [comment]
多谢，我先看看你写的，如果有不会的，还得请教你

**Comment by Gabrielkaliboy** [comment]
@FernandoZhuang 再麻烦一下，这个网易云跟帖我在本地跑的时候可以用，但是布置到线上就不好使，你遇到过这个问题吗？

**Comment by Gabrielkaliboy** [comment]
@FernandoZhuang 已解决，GitHub里面的东西有的没有更新，我把里面的东西全部删除，再次更新提交就好了

**Comment by wangriyu** [comment]
Valine: https://github.com/xCss/Valine
Wildfire: https://github.com/cheng-kang/wildfire
