### ISSUE TITLE
关于图片大小的更改

### ISSUE THREAD

**Issue by shimmeris** [MOxFIVE/hexo-theme-yelee#210]
您好，我想问一下有没有什么方法能修改图片的大小并在图片下方加上一个小标题。
在网上查了一下发现官方提供的标签语法没用，只能用HTML的img标签，觉得有些麻烦，所以有没有在主题里支持能调节大小和显示标题的md语法

**Comment by paradiseduo** [comment]
MarkDown不支持自定义图片大小。

**Comment by ShaneTian** [comment]
@inory009 试试![-w300]()
