### ISSUE TITLE
为什么我的多说评论就是不显示，弄了一天了

### ISSUE THREAD

**Issue by nimdanoob** [MOxFIVE/hexo-theme-yelee#25]
duoshuo: 
  on: true
  domain: zousblog.duoshuo.com
  # 是否开启多说评论，http://duoshuo.com/create-site/
  # 使用上面网址登陆你的多说，然后创建站点，在 domain 中填入你设定的域名
  # http://你的多说域名.duoshuo.com

**Comment by MOxFIVE** [comment]
domain: zousblog
