### ISSUE TITLE
构建的时候报错，请帮忙看看啥原因

### ISSUE THREAD

**Issue by jieli2015** [MOxFIVE/hexo-theme-yelee#27]
The submodule `themes/yelee` was not properly initialized with a `.gitmodules` file. For more information, see https://help.github.com/articles/page-build-failed-missing-submodule.

**Comment by MOxFIVE** [comment]
https://hexo.io/zh-cn/docs/index.html
通过 Hexo 把生成的静态文件传到 GitHub Page 上。

你 github.io 里的文件应该类似下面：
https://github.com/MOxFIVE/MOxFIVE.github.io

**Comment by jieli2015** [comment]
thanks
