### ISSUE TITLE
更新hexo,成功了,但是hexo deploy/generate 命令都用不了,显示not found

### ISSUE THREAD

**Issue by ConanMTHu** [MOxFIVE/hexo-theme-yelee#28]
~/Hexo ❯❯❯ hexo -v
hexo-cli: 0.1.9
os: Darwin 15.3.0 darwin x64
http_parser: 2.5.0
node: 4.2.3
v8: 4.5.103.35
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2e
~/Hexo ❯❯❯ hexo deploy
Usage: hexo

Commands:
help Get help on Hexo.
init Create a new Hexo folder.
version Display version information.

Global Options:
--config Specify config file instead of using _config.yml
--cwd Specify the CWD
--debug Display all verbose messages in the terminal
--safe Disable all plugins and scripts
--silent Hide output on console

For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/

这是什么情况呀?

**Comment by MOxFIVE** [comment]
进入你 Hexo 安装文件所在文件夹再执行相关命令，我的路径是 `/c/data/hexo`，你查下自己的：
``` diff
Holmes@MZH-Win MINGW64 ~
$ cd /c/data/

Holmes@MZH-Win MINGW64 /c/data
$ hexo v
hexo-cli: 0.1.8
os: Windows_NT 10.0.10576 win32 x64
http_parser: 2.5.0
node: 4.2.1
v8: 4.5.103.35
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2d

Holmes@MZH-Win MINGW64 /c/data
+ $ cd /c/data/hexo

Holmes@MZH-Win MINGW64 /c/data/hexo
+ $ hexo v
hexo: 3.1.1
os: Windows_NT 10.0.10576 win32 x64
http_parser: 2.5.0
node: 4.2.1
v8: 4.5.103.35
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2d
```

**Comment by aimer1124** [comment]
确认下，是不是使用hexo init 生成的文件夹
`
$ hexo init blog
$ cd blog
$ npm install
`
