### ISSUE TITLE
文章中插入图片的样式问题

### ISSUE THREAD

**Issue by heypnus** [MOxFIVE/hexo-theme-yelee#3]
举例：写文章时插入以下代码
\<img src="/img/test.jpeg" style="width: 100px;"/>
在其他主题下，可以成功改变图片大小；但是在yelee主题下，图片还是会被拉伸到全屏，求解。
谢谢！

**Comment by MOxFIVE** [comment]
图片样式受 fancybox 模块控制，在主题 `_config.yml` 里关闭 fancybox 即可。
```
fancybox: false
```

**Comment by heypnus** [comment]
明白了，谢谢！

**Comment by MOxFIVE** [comment]
做了些小改进，现在可以只在某篇文章中关闭 fancybox ，[参考这里](https://github.com/MOxFIVE/hexo-theme-yelee#4-style-image-自定义图片样式)。

**Comment by MOxFIVE** [comment]
```html
<img src="/test.jpg" width="150px" height="50px" title="test"/>
```

**Comment by RanchoCooper** [comment]
可以按百分比(保持长宽比)来改大小吗
