### ISSUE TITLE
操作图标颜色有点浅，哪里可以修改啊？

### ISSUE THREAD

**Issue by dxjia** [MOxFIVE/hexo-theme-yelee#31]
感谢作者的主题，很漂亮。

文章页面里的一些操作图标都是白色的，比如 返回顶部和底部 ![bottom_up](http://7xqitw.com1.z0.glb.clouddn.com/back_up.jpg)， 上一篇 下一篇![pre_next](http://7xqitw.com1.z0.glb.clouddn.com/pre_next.jpg)，很不容易看到。。。可以改为深色的吗？或者哪里可以自定义呢？

谢谢。。。

**Comment by MOxFIVE** [comment]
没有地方设置，有需要可自行修改 CSS
https://github.com/MOxFIVE/hexo-theme-yelee/blob/master/source/css/_partial/main.styl

```stylus

/* 返回顶部和底部 */
.scroll {
    a {
        background: rgba(215, 216, 215, .4); /* 背景色 */
        .fa {
            color: rgba(255, 255, 255, .8); /* 图标颜色 */
        }
}

/* 上一篇 下一篇 */
#post-nav-button {
    a {
        background: none;
    }

```

**Comment by dxjia** [comment]
Thanks，按你说的成功了。。。。

**Comment by mlijin9011** [comment]
背景色可以改，但是图标颜色改了没效果呢
