### ISSUE TITLE
markdown 列表支持有问题

### ISSUE THREAD

**Issue by rushingFiend** [MOxFIVE/hexo-theme-yelee#32]
当输入以下 markdown 时

1. test
    * test

        test
    * test
2. test

出来的效果有问题，话说要怎么在这里贴图片来着。。。。

**Comment by MOxFIVE** [comment]
主题自定义了无序列表的样式，兼容性不是很好。你可以修改成像 GitHub 显示的小圆圈。

https://github.com/MOxFIVE/hexo-theme-yelee/blob/master/source/css/_partial/article.styl#L163
```stylus
  ul{
    li:before{
      display inline-block;
      content: "";
      width: .4em;
      height: .4em;
      margin-right: .5em;
      margin-bottom: .11em;
      border: 1px solid lightgray;
      border-radius: 50%;
      background: lightgray;
    }
  }
```

> 删掉上面代码，用下面的替换

```css
ul li {
    list-style-type: circle;
    margin-left: 1.2em;
}
```

贴图: 直接把图片托到评论框

**Comment by rushingFiend** [comment]
![eefc2253-d5bb-447a-afc5-2e2ff82c7dd2](https://cloud.githubusercontent.com/assets/8984682/12705552/a8638fe2-c8ae-11e5-9ff8-dbddfb0d6fbf.jpg)

按你说的处理了之后还是有问题。。是不是跟有序列表的兼容性也有关？

**Comment by MOxFIVE** [comment]
我的疏漏，下面的样式也要改一下，`ul`去掉：
https://github.com/MOxFIVE/hexo-theme-yelee/blob/master/source/css/_partial/article.styl#L180
```diff
  li{
-   ul,ol{
+   ol {
      margin-left: 30px;
      li:before{
        content: "";
        background: #dedede;
      }
    }
  }
```

![snip20160201_1](https://cloud.githubusercontent.com/assets/10032927/12708217/27ad18c6-c8d8-11e5-94ec-865c1953bbdd.png)

**Comment by rushingFiend** [comment]
嗯嗯，可以了，谢谢！！
