### ISSUE TITLE
可以增加虾米的subnav 嘛？

### ISSUE THREAD

**Issue by Arondight** [MOxFIVE/hexo-theme-yelee#34]
不知道可不可以请求加一个[虾米](http://www.xiami.com/u/6110365)的（厚脸皮）
如链接所见，虾米的链接可以通过指定UID 来搞定。
如果感觉加上不适合的话直接close 掉就可以咧 。
非常感谢你的主题 (╭￣3￣)╭♡

**Comment by Arondight** [comment]
如果有需要的话logo 可以在[这里](http://www.xiami.com/links)得到

**Comment by MOxFIVE** [comment]
你可以参考上面的 commit 添加图标；
还是填完整链接，和其他保持一致，避免混淆。

**Comment by Arondight** [comment]
3Q
