### ISSUE TITLE
最新版不能正常使用

### ISSUE THREAD

**Issue by ShinoharaYuri** [MOxFIVE/hexo-theme-yelee#36]
今天重裝了Hexo和最新版主題

    hexo: 3.1.1
    os: Linux 4.1.13-v7+ linux arm
    http_parser: 2.6.0
    node: 5.5.0
    v8: 4.6.85.31
    uv: 1.8.0
    zlib: 1.2.8
    ares: 1.10.1-DEV
    icu: 56.1
    modules: 47
    openssl: 1.0.2e

Hexo+主題 沒有修改任何選項 
首頁和post目錄的東西不顯示
沒在 /source/_posts/ 的 比如 /source/404/ 可以正常顯示

**Comment by MOxFIVE** [comment]
我試著新安裝了 Hexo 和主題，文章可以正常顯示
```
$ hexo v
hexo: 3.1.1
os: Windows_NT 10.0.10576 win32 x64
http_parser: 2.5.0
node: 4.2.1
v8: 4.5.103.35
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2d
```

沒安裝 Linux，不清楚是不是主題在 Linux 下兼容性不好。
你可以下載主題歷史版本試試，下載后解壓到 `themes` 資料夾，覆蓋源文件或者作為新主題

![snip20160208_3](https://cloud.githubusercontent.com/assets/10032927/12881644/508df3ec-ce86-11e5-9d74-a6194db18764.png)

**Comment by ShinoharaYuri** [comment]
剛測試了一下好了
抱歉 可能是吾輩這邊當時抽風而已
沒有做過多測試就就開issue真是抱歉
應該換設備多測試一下的
