### ISSUE TITLE
请求加入百度统计

### ISSUE THREAD

**Issue by ljfxyj2008** [MOxFIVE/hexo-theme-yelee#39]
博主你好，你的主题目前支持google统计，但是由于墙的原因，国内用户在访问页面时对google统计的回调可能失败，导致统计不准确。
能否把百度统计的代码也加进来。

**Comment by MOxFIVE** [comment]
百度统计提供的代码: http://sitecenter.baidu.com/sc-web/
```html
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "//hm.baidu.com/hm.js?a4938c90e05043bd9774ff12368e45aa";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>
```

主题配置中填写示例: 
```
baidu_tongji: a4938c90e05043bd9774ff12368e45aa
```

**Comment by Arondight** [comment]
其实可以把统计代码和google 统计放到同一个ejs 里方便管理，之前手动加到同一个的，测试没有问题。

可以参见[这里](https://github.com/Arondight/arondight.github.io/commit/d7e802b569b29d9fa2d140621adfb3832128bfca)。

**Comment by MOxFIVE** [comment]
@Arondight 都可以，直接放在 head 里统计可能会更精确一些
