### ISSUE TITLE
Hexo post with several categories 文章设置多个分类后的问题

### ISSUE THREAD

**Issue by MOxFIVE** [MOxFIVE/hexo-theme-yelee#4]
![snip20151112_3](https://cloud.githubusercontent.com/assets/10032927/11118565/c625968a-897d-11e5-9ab4-11119cb396a3.png)
According to my observation, in Hexo (3.1.0), when a post is applied with several categories like below:
```
categories:
- Life
- Work
- Study
```
The post will be count **ONLY** in the very first set category `Life`, and two tree categories `Life/Work` and `Life/Work/Study` will be generated. Categories after `Life` will be treated as its children which can be verified in source code.

In the post, clinking `Life` will jump to `Life` category page,  clinking `Work` will jump to `Life/Work`s, and clicking `Study` will jump to `Life/Work/Study`s.
```
/categories/Life/
/categories/Life/Work/
/categories/Life/Work/Study/
```
为 Hexo 文章设置多个分类后，只算入第一个分类，同时 Hexo 会从当前分类列表生成类似文件夹那样的层级分类（点击文章中不同分类标记即跳转到对应层级分类页面）。

<http://moxfive.xyz/tags/>

**Comment by Arondight** [comment]
[hexo #1787][ID_1787]

[ID_1787]: https://github.com/hexojs/hexo/issues/1787 "一个post 无法指定大于一个categories"

**Comment by RanchoCooper** [comment]
如何生成分类的页面呢

**Comment by llianc62** [comment]
标签云两层一样的，这么解决了，不能跳到文章目录页面  https://liangxiansen.github.io/tags/

**Comment by Gabrielkaliboy** [comment]
老大，我英语不是很好，可不可以给来个中文注解。。。

**Comment by RanchoCooper** [comment]
自行查单词

**Comment by Durant35** [comment]
Waiting for https://github.com/danieljsummers/hexo/commit/62cbd3f3eda1852c0c6814f1cb3d6202dd071258 merged!!!
> https://github.com/hexojs/hexo/issues/848

**Comment by Durant35** [comment]
**hexo: 3.4.2** 亲测有效
+ 语法
![image](https://user-images.githubusercontent.com/6770853/33260036-ac16f3d4-d399-11e7-9deb-1ad52114882b.png)
+ 分类栏
![image](https://user-images.githubusercontent.com/6770853/33260077-c32559e4-d399-11e7-8891-c8fb55e26654.png)
+ 可以改进的地方：左下角归档根据不同分级给颜色？
![image](https://user-images.githubusercontent.com/6770853/33260129-e8df55f4-d399-11e7-9ba2-fe7e9a161be3.png)

**Comment by EruDev** [comment]
想知道怎么生成分类和标签, 可以丢个命令啥的吗

**Comment by zacSuo** [comment]
category始终是跟tag在一起的，无法独立出来的
![image](https://user-images.githubusercontent.com/4320791/51251009-35a04300-19d3-11e9-9efd-1f7d0be6ea04.png)

**Comment by ShaneTian** [comment]
[亲测可用](https://suixinblog.cn/tags/)
1. 多分类（平行级别）：
```
categories:
- [Linux,]
- 技术驿站
```
实现同一文章多个分类。

2. 多分类（树状）：
```
categories:
- [Linux, 技术驿站]
# 或者
categories:
- Linux
- 技术驿站
```
会产生层级分类结构：`/categories:/Linux/技术驿站/`
