### ISSUE TITLE
change background

### ISSUE THREAD

**Issue by ifibercc** [MOxFIVE/hexo-theme-yelee#40]
请问背景图的长宽应为什么，另外配置为0的时候的灰白背景样式可以在什么地方修改，谢谢

**Comment by MOxFIVE** [comment]
背景图使用一般的宽屏壁纸就行，没有严格限制，可以多换换尝试效果。
图片建议使用 http://zhitu.isux.us/ 压缩，品质选低些，以减少体积和优化页面加载速度。

yelee/layout/_partial/[background.ejs](https://github.com/MOxFIVE/hexo-theme-yelee/blob/master/layout/_partial/background.ejs) 
```html
<% } else { %>
    <style>
        /*关闭背景后的样式*/
    </style>
<% } %>
```

**Comment by ifibercc** [comment]
很详细，非常感谢
