### ISSUE TITLE
访问网站时会不停发送请求

### ISSUE THREAD

**Issue by ljfxyj2008** [MOxFIVE/hexo-theme-yelee#41]
用这个主题，用chrome访问我的网站时打开开发者工具的"network"中看到，一直在发送一个请求，像是死循环，如图：
![chrome_site](https://cloud.githubusercontent.com/assets/9248679/13202468/21d12fbe-d8d7-11e5-8e04-351d760360c5.PNG)

不知道这是hexo的问题还是这个主题的问题？

**Comment by MOxFIVE** [comment]
不清楚，我这里打开你的网站“请求”是正常的 Mac OS, Chrome
