### ISSUE TITLE
请问怎么不让目录自动生成目录数字号

### ISSUE THREAD

**Issue by maquannene** [MOxFIVE/hexo-theme-yelee#43]
自动生成目录时，会自动在目录前追加数字编号，我怎么去屏蔽掉这个东西。
因为我本身的 md 就已经写了目录编号，怎么去屏蔽掉这个东西。

谢谢

**Comment by MOxFIVE** [comment]
参考下面修改即可
https://github.com/MOxFIVE/hexo-theme-yelee/blob/master/layout/_partial/toc.ejs#L3
```diff
- <%- toc(post.content) %>
+ <%- toc(post.content, {list_number: false}) %>
```

**Comment by maquannene** [comment]
thank a lot
