### ISSUE TITLE
is_page is not defined

### ISSUE THREAD

**Issue by Rearcher** [MOxFIVE/hexo-theme-yelee#44]
Hello, thank you first for the beautiful theme! I met some problem when I generated my blog, the problem is shown in the picture. How to solve it?[http://7pulgx.com1.z0.glb.clouddn.com/Screenshot%20from%202016-02-25%2012-57-24.png](url)
(Open the link in web browser)

**Comment by MOxFIVE** [comment]
Update Hexo to latest version or Install Hexo in a new folder

#26
