### ISSUE TITLE
hexo-theme-yelee移动端侧边栏优化

### ISSUE THREAD

**Issue by Cxuef** [MOxFIVE/hexo-theme-yelee#45]
在手机上浏览时，展开博客/关于我/友链/标签的侧边栏会随着下滑而滚动，显得很突兀。如截图：
![Screenshot](http://7xqbln.com1.z0.glb.clouddn.com/eirotScreensho.jpeg)

**Comment by MOxFIVE** [comment]
在我手机上显示正常，大概是兼容性问题，具体原因不详

**Comment by Cxuef** [comment]
恩，我现在也不能复现了。手机浏览器是UC，这个问题是偶现的
