### ISSUE TITLE
一个post 无法指定大于一个categories

### ISSUE THREAD

**Issue by Arondight** [MOxFIVE/hexo-theme-yelee#48]
categories 指定多个，文章能够显示多个categories，但是实际在`/categories/` 中只有一个生效。

**Comment by MOxFIVE** [comment]
参考 [#4: Hexo post with several categories 文章设置多个分类后的问题](https://github.com/MOxFIVE/hexo-theme-yelee/issues/4)

**Comment by Arondight** [comment]
问一下这个是hexo 的共性问题还是yelee 的特有问题呀

**Comment by Arondight** [comment]
试了下别的theme 也有这个问题。

**Comment by Arondight** [comment]
[hexo #1787][ID_1787]

[ID_1787]: https://github.com/hexojs/hexo/issues/1787 "一个post 无法指定大于一个categories"
