### ISSUE TITLE
取消网页背景图后视觉效果很差

### ISSUE THREAD

**Issue by ge-ce** [MOxFIVE/hexo-theme-yelee#49]
我比较喜欢简洁，所以不太喜欢透明化背景和背景图片。

但是设置 `background_image: 0` 之后的效果很差，整个网页显得很苍白，好像是背景和字体颜色很浅吧。还是更喜欢 `Yilia` 主题的配色，怎么简单的修改一下？

**Comment by zwj47** [comment]
在header.ejs 下面 style标签里面改自己想要的颜色就可以啦

**Comment by MOxFIVE** [comment]
更新主题，配置填写
```
color_scheme: yilia
```
文章标题样式暂不调整，因为以后会单独设置

![snip20160302_3](https://cloud.githubusercontent.com/assets/10032927/13461668/e7ea80f4-e0bd-11e5-9d20-547c74717d8b.png)

**Comment by Arondight** [comment]
非常喜欢，给你32 个赞
