### ISSUE TITLE
关于多说的问题

### ISSUE THREAD

**Issue by liujieds** [MOxFIVE/hexo-theme-yelee#5]
在-config.yml中设置了多说：（我的key） ，但是生成的页面却没显示存在多说，不知道是什么问题

**Comment by MOxFIVE** [comment]
确保你在主题`Yelle\_config.yml` 文件里启用了多说，并填入正确地 key，同时文章中没有用 `comments: false` 关闭评论。
```
duoshuo: 你的key
```

**Comment by liujieds** [comment]
给个qq吧，我给你qq上截图给你看，还是没有多说

**Comment by liujieds** [comment]
3Q 已解决
