### ISSUE TITLE
文章中表格显示不正确？

### ISSUE THREAD

**Issue by dxjia** [MOxFIVE/hexo-theme-yelee#50]
不知道这个问题是否应该在这里问，因为我使用markdown语法绘制的表格在生成的文章里不能正确显示。。。我用其他markdown编辑器可以。是主题不支持吗？ 
比如下面的表格：
| A  | B|
| :-------- | :--------|
| 1  | This is a sample. |
|2  | This is a sample. |

**Comment by MOxFIVE** [comment]
我用你上面的源码试了一下，可以正常显示

![snip20160303_1](https://cloud.githubusercontent.com/assets/10032927/13497012/33114240-e18e-11e5-9fad-fa3ecab7797e.png)

**Comment by dxjia** [comment]
不好意思，是我的问题，在表格开头加了个回车问题解决。
close。

**Comment by BenjaminXi** [comment]
我也碰到了相同的问题，都是没有回车
