### ISSUE TITLE
左侧的页面区域能够在配置中调整大小或者自适应吗？

### ISSUE THREAD

**Issue by Arondight** [MOxFIVE/hexo-theme-yelee#51]
[情况是这样的](http://arondight.me)，一共6 个页面，但是只能显示5 个，最后一个需要拉进度条。

不知道能不能手动调整大小（这个方案似乎比自适应要好）

**Comment by Arondight** [comment]
或者可以自适应，但是配置文件字段有值的话以配置文件为准？

**Comment by MOxFIVE** [comment]
https://github.com/MOxFIVE/hexo-theme-yelee/blob/master/source/css/_partial/main.styl#L155
```stylus
.header-menu
    max-height: menu-line-height * 5px;
```
你把 5 改成 6 就行了。屏幕高度不够时，下面的社交图标可能无法展示，所以菜单多于 5 个时，显示滚动条。

**Comment by Arondight** [comment]
3q
