### ISSUE TITLE
哪里可以配置标题的样式

### ISSUE THREAD

**Issue by dxjia** [MOxFIVE/hexo-theme-yelee#54]
请教在哪里可以修改标题的样式，比如 h1, h2, h3....等等，谢谢。。。

**Comment by zwj47** [comment]
source - css- _partial - article.styl

**Comment by dxjia** [comment]
@zwj47 谢谢。
我尝试修改了一下这里的h1, h2的配置，本地 hexo s ， localhost:4000 访问，会看到修改后的效果；
可为何部署上去，就还是原来的效果呢。。。好困惑，我是所有文件全部替换的。。。

**Comment by zwj47** [comment]
hexo他这个有BUG.你先把之前生成的css/style.css 删除后,重新 hexo g 才会是改过后的.

**Comment by dxjia** [comment]
@zwj47 
Thanks, 按你说的解决啦。多谢。。。。
