### ISSUE TITLE
用了这个主题之后localhost一切正常

### ISSUE THREAD

**Issue by iMissWonder** [MOxFIVE/hexo-theme-yelee#57]
但是deploy后很大一部分都不显示了，求解为什么呀！！刚开始起步
现在就这样：http://imisswonder.com/
用原本的yilia主题没有问题……真是闹心

**Comment by MOxFIVE** [comment]
不清楚原因，尝试用下面的代码 deploy 部署
```
hexo clean && hexo d
```
不行的话，关掉 git 窗口，删掉 Hexo 根目录下的 `db.json` 和 `.deploy_git` 文件夹后再用上面的方法部署

**Comment by zwj47** [comment]
有一处jquery.js 的资源错误.检查一下

**Comment by iMissWonder** [comment]
谢谢，我把之前自己折腾的删了重新弄了一遍主题，现在已经好了！
