### ISSUE TITLE
关于标签和 GitHub 图标的问题

### ISSUE THREAD

**Issue by limaofuyuanzhang** [MOxFIVE/hexo-theme-yelee#61]
你好，感谢你的主题，感觉非常好看。在这想请教一些问题，hexo在读取tag时是从上往下读还是从下往上读的呢？这个是主题决定的还是hexo就已经决定好的？为什么我的博客中有的标签是从第一个开始显示而有的又是从最后一个显示？

**Comment by limaofuyuanzhang** [comment]
还有一个问题，更新到最新版后github图标显示一片空白

**Comment by MOxFIVE** [comment]
GitHub 图标问题: 到你的仓库里把 `github.png` 改成 `GitHub.png`
https://github.com/limaofuyuanzhang/limaofuyuanzhang.github.io/tree/master/img

标签顺序问题: Hexo 标签默认是按升序 abc 排，应该和书写顺序无关
https://hexo.io/zh-cn/docs/helpers.html#list-tags

**Comment by limaofuyuanzhang** [comment]
你好，非常感谢～图片似乎是由于以前用的是github.png，而现在变成GitHub.png，但是github并没有把文件名的大小写变化当成是改变导致没有上传新图片是吗？我想到的是先在本地删除GitHub.png，提交，再把GitHub.png放回去，再提交，但似乎这种解决方案并不优雅。能否请教一下是否有更好的处理方法呢？

**Comment by MOxFIVE** [comment]
根治：Git 设置对文件名大小写敏感
```yaml
# 编辑 Git 配置文件 config
路径: <Hexo根目录>\.deploy_git\.git\config 
```

```diff
- ignorecase = true

+ ignorecase = false
```
