### ISSUE TITLE
标签云那里能否将生成子目录

### ISSUE THREAD

**Issue by limaofuyuanzhang** [MOxFIVE/hexo-theme-yelee#62]
如题，目前的标签云那页只能看到第一级目录，是否有设置可以将二级目录三级目录也显示出来呢？

**Comment by MOxFIVE** [comment]
列出多级目录的话样式有点乱，统计也不准确，权衡之下我只保留第一级目录，有需要的你可以尝试修改

参考：https://github.com/MOxFIVE/hexo-theme-yelee/commit/8f00171371af03682c774049d00b0172f8ccbbcf

**Comment by limaofuyuanzhang** [comment]
好的，谢谢
