### ISSUE TITLE
代码高亮BUG

### ISSUE THREAD

**Issue by Arondight** [MOxFIVE/hexo-theme-yelee#63]
指定代码段类型为`c`，下面的Markdown 无法生成高亮代码，查看HTML 发现`<figure class="highlight">`

```
tcpsumblock = (char *)malloc (packetSize * sizeof (char));
```

下面的可以正常高亮，对应HTML`<figure class="highlight c">`

```
tcpsumblock = (char *)malloc (packetSize);
```

**Comment by MOxFIVE** [comment]
我尝试切换到默认主题同时手动指定代码类型，依旧无高亮。
Hexo 代码高亮使用的是 [highlight.js](https://github.com/isagalaev/highlight.js) 插件，应该是插件的问题，无法通过主题修复。

**Comment by Arondight** [comment]
3Q
