### ISSUE TITLE
标签云页面直接跳转404

### ISSUE THREAD

**Issue by fanff0324** [MOxFIVE/hexo-theme-yelee#65]
## 标签云无法正常显示
按照正常设定，标签云的地址应该是：http://"主页"/tags
但是目前生成出来是无法打开的一个页面。（在tags文件下下缺失index.html？）
现在去我的博客无论是点击侧边栏的”标签云“，还是在地址栏中输入http://"主页"/tags都会直接跳转404页面（也就是不存在）

## 详细情况
已经自检过了，目前侧边栏（sitemap）的配置如下：
``` bash
menu:
  主页: /
  归档: /archives/
  标签云: /tags/
  关于我: /about/
```
这种问题怎么解决呢？

**Comment by MOxFIVE** [comment]
看起来你好像没有新建页面，about 和 tags 页面都要在手动建立
https://github.com/MOxFIVE/hexo-theme-yelee#1-about-page-关于我页面

**Comment by fanff0324** [comment]
我重新看一下readme和你的教程好了
