### ISSUE TITLE
favicon的选择

### ISSUE THREAD

**Issue by fanff0324** [MOxFIVE/hexo-theme-yelee#66]
抱歉我又来打扰了。
favicon的style在哪里？现在虽然是跟随你的png图片设置在用着图标，但是在之前我用landscape的时候使用的是自己制作的favicon.ico。在yelee主题下无论是放在yelee的source下还是hexo的source下都没有作用。如果想还原之前的favicon，要怎么处理呢？

**Comment by ShinoharaYuri** [comment]
# Small icon of Your site | 站点小图标地址
    favicon: /favicon.png
請修改這裡
