### ISSUE TITLE
代码样式的如何设置，还可选择的背景色如何去掉

### ISSUE THREAD

**Issue by zhonghanwen** [MOxFIVE/hexo-theme-yelee#67]
我现在的代码样式是这样子的，没有显示出行号以及代码没有高亮。![image](https://cloud.githubusercontent.com/assets/12220537/14102044/e4f67ebc-f5ca-11e5-99b8-b7749b4f7c21.png)
请问如何修改配置可以变成以下这种样式？
![image](https://cloud.githubusercontent.com/assets/12220537/14102050/f6197aa0-f5ca-11e5-9973-0fdc3ff3bc43.png)

**Comment by MOxFIVE** [comment]
代码块用下面方法添加：https://github.com/MOxFIVE/hexo-theme-yelee/commit/46c25d394f9302fead06b27674df87b61d52eec3

\`\`\`
code
\`\`\`

主题配置中启用自定义样式
```yaml
highlight_style:
  on: true
```

**Comment by tomorOoO** [comment]
## General Color Scheme | 主题配色方案 
## 可用值 Value: yilia
color_scheme:

highlight_style:
  #on: true
  inline_code: 9  # Value: 0 - 9 可选
  code_block: 3  # Value: 0 - 4 

我已经这样设置过了,但是代码那里依旧无变化

**Comment by MOxFIVE** [comment]
@tomorOoO , 去掉 `#` 才生效
```diff
- #on: true
+ on: true
```
