### ISSUE TITLE
tags還是簡體

### ISSUE THREAD

**Issue by ShinoharaYuri** [MOxFIVE/hexo-theme-yelee#70]
已有 0 个分类， 共计 0 个标签。

**Comment by MOxFIVE** [comment]
‎這部分代碼準備調整，所以暫時沒有去翻譯

Sent from my BlackBerry 10 smartphone.
From: ShinoharaYuri
Sent: 2016年4月7日星期四 10:53
To: MOxFIVE/hexo-theme-yelee
Reply To: MOxFIVE/hexo-theme-yelee
Subject: [MOxFIVE/hexo-theme-yelee] tags還是簡體 (#70)



已有 0 个分类， 共计 0 个标签。
