### ISSUE TITLE
标签 没背景色 怎么调 只有鼠标指上的时候才有背景色？？？

### ISSUE THREAD

**Issue by RunningYoung** [MOxFIVE/hexo-theme-yelee#73]
![97e66d96-700d-479e-b21d-4d880a238a74](https://cloud.githubusercontent.com/assets/7145734/14448474/8fcfc002-009b-11e6-9438-cc0087189b03.png)

**Comment by MOxFIVE** [comment]
你网站并不是存放在子目录，下面这个配置请留空：
```diff
- root_url: https://runningyoung.github.io
+ root_url: 
```

**Comment by RunningYoung** [comment]
已经留空格了 还是不好使 就是标签 没背景色 你可以去看看 https://runningyoung.github.io  标签全是白色的 看不到 郁闷了

**Comment by RunningYoung** [comment]
大哥 你知道怎么解决吗 没解决问题啊

**Comment by MOxFIVE** [comment]
看 2L 的配置，是删掉，不是留空格，我看了你网站源码，里面还是 `yiliaConfig.rootUrl = https://runningyoung.github.io;`，正确的应该是 `yiliaConfig.rootUrl = "/";`

**Comment by RunningYoung** [comment]
好的 刚看明白 我试试 多谢了
