### ISSUE TITLE
代码高亮问题

### ISSUE THREAD

**Issue by dongjiahong** [MOxFIVE/hexo-theme-yelee#74]
```cpp
class Test{
  explicit Test(std::thread& t_ ):t(t_){}
};
```

```cpp
class Test{
  void Test(){}
} 
```

有 explicit 关键字就不高亮

**Comment by MOxFIVE** [comment]
代码高亮问题建议到 [Hexo](https://github.com/hexojs/hexo) 或 [highlight.js](https://github.com/isagalaev/highlight.js) 项目下咨询
http://dwz.cn/374pYB
