### ISSUE TITLE
请问为什么tag和category图标颜色都不对呢？

### ISSUE THREAD

**Issue by james97** [MOxFIVE/hexo-theme-yelee#79]
请看这里 http://james97.github.io/Jun-blog/， 设置这两个的代码在哪个文件呢？谢谢

**Comment by MOxFIVE** [comment]
```yaml
root_url: /Jun-blog/
```
需在主题配置内填写子目录信息
https://github.com/MOxFIVE/hexo-theme-yelee/blob/master/_config.yml#L29

**Comment by james97** [comment]
原来如此，我还以为hexo的config里面设置了就好。解决了，谢谢
