### ISSUE TITLE
Coding(Gitcafe)和GitHub的路由问题

### ISSUE THREAD

**Issue by AsanZhang** [MOxFIVE/hexo-theme-yelee#89]
博主是如何将国内的ip方位路由到GitCafe上，而国外方位路由到GitHub上的？[如V2EX上所说](https://www.v2ex.com/t/228990)

**Comment by MOxFIVE** [comment]
我现在只托管在 GitHub 了，不过分流方法应该还是如下文所述
http://ohroot.com/2016/04/12/hexo-deploy-with-github-and-coding/

**Comment by AsanZhang** [comment]
@MOxFIVE 好的，我完了试试可以不。
