### ISSUE TITLE
表格中的内容过多时会超出显示区域而不会自动换行

### ISSUE THREAD

**Issue by heypnus** [MOxFIVE/hexo-theme-yelee#9]
请问除了手动加\<br\>之外，有没有其他普适性更好、更简便的方法？谢谢！

**Comment by MOxFIVE** [comment]
我以前为了方便自己，设置了标题行 和 前三列不换行，可能是这个影响到你的表格。

282行 和 302 行
[/source/css/_partial/article.styl#L282](https://github.com/MOxFIVE/hexo-theme-yelee/blob/master/source/css/_partial/article.styl#L282)

**Comment by heypnus** [comment]
试过了果然是这个原因……谢谢！
