### ISSUE TITLE
关于百度、Swiftype 和本地搜索  Local live search

### ISSUE THREAD

**Issue by hnuzhoulin** [MOxFIVE/hexo-theme-yelee#90]
Swiftype可以实现站内搜索而无需被搜索引擎收录

请问是否考虑添加

**Comment by hnuzhoulin** [comment]
我尝试照着http://www.jerryfu.net/post/search-engine-for-hexo-with-swiftype-v2.html 
这个来做，但是发现最终的首页显示文章的那部分CSS被改变了，有个时候首页右边部分全是空白。。。

希望能够支援

**Comment by MOxFIVE** [comment]
Swiftype 好久没折腾了，情况不大清楚。
我打算在主题里添加本地搜索引擎，第三方搜索服务暂不考虑
http://hahack.com/codes/local-search-engine-for-hexo/

**Comment by hnuzhoulin** [comment]
当然能有本地搜索是最佳选择。静候佳音。多谢。我会先试一试的

**Comment by MOxFIVE** [comment]
### Hexo Local Live Search Demo: http://moxfive.xyz/
![gif](https://cloud.githubusercontent.com/assets/10032927/15427680/56b96894-1ec9-11e6-810e-42bfb3e26e32.gif)

> 本地搜索大概就是这样，目前只应用在自己的博客，等测试好后会整合到主题中

**Comment by Arondight** [comment]
有的搜索内容是不是太长了，边栏本来就很窄，太长了似乎不太方便

**Comment by MOxFIVE** [comment]
### New DEMO http://moxfive.xyz/

![gif](https://cloud.githubusercontent.com/assets/10032927/15540813/fa70996c-22bb-11e6-8808-cae1a913ae02.gif)

**Comment by Arondight** [comment]
问下搜索的时候好像边栏原本的内容没有隐藏，而是跑到了搜素内容的下面，设计如此？

**Comment by MOxFIVE** [comment]
是的，我觉得没什么影响就保留了

**Comment by hnuzhoulin** [comment]
亲，我pull你的最新代码，但是没有你的截图里面的效果啊。
输入搜索字符回车后跳到 url?q=***

我在你的博客上也试了下貌似一样啊。。。。

我的  www.itzhoulin.com

**Comment by hnuzhoulin** [comment]
oops，你的博客是首页不行，但是内容页可以出来搜索内容。。

**Comment by MOxFIVE** [comment]
@hnuzhoulin 在配置中启用 jQuery UI，或者更新主题，搜索应该就正常了

**Comment by weleen** [comment]
@hnuzhoulin 请问最后问题解决了吗？我的配置完了还是不能搜索

**Comment by weleen** [comment]
@hnuzhoulin 安装hexo-generator-search插件的时候位置错了，现在可以搜索了

**Comment by hnuzhoulin** [comment]
@weleen   位置错了？是要在主题目录下安装吗？

**Comment by hnuzhoulin** [comment]
@MOxFIVE   多谢，原来是没有启用jQuery
