### ISSUE TITLE
问个小问题

### ISSUE THREAD

**Issue by RanchoCooper** [MOxFIVE/hexo-theme-yelee#91]
怎么在subnav添加诸如github之类的信息
(把小图标放到/source/img里面显示不出来)

**Comment by MOxFIVE** [comment]
参考之前的 commit https://github.com/MOxFIVE/hexo-theme-yelee/commit/41beb86dd348c659bec430339842561f74e16d28 ，图片名字与 class 名字需一致

感觉你博客部署时有点问题，因为无关的文件有点多，你可以对比一下
这是我部署后的 `img` 文件夹
https://github.com/MOxFIVE/MOxFIVE.github.io/tree/master/img
下面是你的
https://github.com/RanchoCooper/RanchoCooper.github.io/tree/master/img

**Comment by RanchoCooper** [comment]
弄好了 : )
而且我还发现, 图片名为字母的话, 开头必须大写, 不然显示不了

**Comment by RanchoCooper** [comment]
再问下, 如果我想把文章里的图片加上圆角
然后在主页的文章列表(archive-article??)加上box-shadow
应该咋弄啊
