### ISSUE TITLE
win10 chrome 侧边栏问题

### ISSUE THREAD

**Issue by huangjj27** [MOxFIVE/hexo-theme-yelee#92]
当在把chrome的宽度减小到一定程度切换成手机界面的时候没有办法打开侧边栏

**Comment by MOxFIVE** [comment]
那个侧边栏菜单只响应触按 (touch)，不响应鼠标点击 (click)，
Chrome 中可以利用开发者工具模拟打开边栏：
http://jingyan.baidu.com/article/6079ad0e84779728fe86db67.html

**Comment by huangjj27** [comment]
有的的读者一定不会愿意打开模拟器来浏览的，这样子看着不爽。
尤其是要半屏幕参考博客，半屏幕自己动手操作的时候会很不方便吧
