### ISSUE TITLE
你好，请问一下怎么设置版权信息在电脑是上面显示 在手机上面不显示呢

### ISSUE THREAD

**Issue by ydx1013** [MOxFIVE/hexo-theme-yelee#93]
你好，我非常喜欢你的主题，请问一下我想在电脑的版权信息后面放上一个我的微信的二维码，但是又不想在手机上面显示，手机上面空间太小了。希望能够解答一下我应该怎么做，谢谢。

**Comment by MOxFIVE** [comment]
在下面的文件中设定移动端样式：
```
/source/css/_partial/mobile.styl
```

假设你添加的二维码相关代码如下：
```html
<img class="barcode" src="/barcode.jpg">
```

在移动端隐藏该图，把下面代码添加到`mobile.styl`即可：
```css
.barcode { display: none; }
```

**Comment by ydx1013** [comment]
你好 我按照你的方法  把二维码添加到了left-col.ejs里面的   aboutme  后面  然后在mobile.styl里面添加.barcode { 
    display: none; 
}可是  手机界面还是显示啊  是不是我哪里写错了。我不懂代码 不好意思哈。

**Comment by MOxFIVE** [comment]
那我也不清楚了，你试试 `.barcode { display: none; !important }`，理论上 `left-col.ejs` 里加的东西，移动端是不显示的

**Comment by ydx1013** [comment]
嗯，我试了下貌似不行。  谢谢你了 。我不折腾了 等你更新吧，嘿嘿
