### ISSUE TITLE
苣苣考虑给一级标题来点特效吗？

### ISSUE THREAD

**Issue by Arondight** [MOxFIVE/hexo-theme-yelee#94]
# duang

**Comment by MOxFIVE** [comment]
一开始我是拒绝的。

一是文章标题已经是一级了，那正文似乎该从二级开始；
二是一个网页中一级标题最好只使用一次，利于 SEO；
三、感觉默认的二、三级标题已经有点花哨了，再加特效要眼花缭乱了；

# 四、我不知道要加什么特效。

**Comment by Arondight** [comment]
# 我一直以为段落要用一级标题的

## 原来是要用二级

扑通

**Comment by jp1017** [comment]
:six: :six: :six:
