### ISSUE TITLE
有没有隐藏文章的功能？

### ISSUE THREAD

**Issue by huangjj27** [MOxFIVE/hexo-theme-yelee#96]

**Comment by MOxFIVE** [comment]
这么并没有，你可以新建页面，这样知道对应页面链接才能访问
http://moxfive.xyz/2015/12/21/common-hexo-commands/#hexo-n-page

**Comment by huangjj27** [comment]
从文章历史信息的经验出发，利用github的版本管理系统实现了手动的隐藏文章的功能，可以比较个性化地定制隐藏。其实本质上就是不部署到github.io上，但是可以存有文章的修改记录
http://172.18.42.8:4000/2016/05/16/hide-ariticle-with-github/
