### ISSUE TITLE
mathjax公式没有办法正常显示

### ISSUE THREAD

**Issue by huangjj27** [MOxFIVE/hexo-theme-yelee#97]
代码如下：
$$
h{\theta}(x) = \theta ^ t \cdot x \
J(\theta) = \frac{1}{2}(y-h{\theta}(x))^2
$$

**Comment by MOxFIVE** [comment]
需要主题配置中开启 MathJax
```yaml
# Display Math(LaTeX, MathML...) | 数学公式支持
mathjax: true
```

**Comment by huangjj27** [comment]
主题配置没有效果，最后在博客配置上增加了hexo-math插件解决。

**Comment by Seraphli** [comment]
注意：公式中的下划线会被markdown误认为是斜体格式而被转换掉，使用`\_`来跳过这种转换
