### ISSUE TITLE
署名 - 非商用 - 相同方式共享 4.0 還是簡體

### ISSUE THREAD

**Issue by ShinoharaYuri** [MOxFIVE/hexo-theme-yelee#98]
許可協議: "署名 - 非商用 - 相同方式共享 4.0" 轉載請保留原文鏈接及作者。

**Comment by MOxFIVE** [comment]
簡繁體似乎是一樣的
```yaml
# 简体
许可协议: "署名-非商用-相同方式共享 4.0" 转载请保留原文链接及作者。

# 繁体
許可協議: "署名-非商用-相同方式共享 4.0" 轉載請保留原文鏈接及作者。
```

**Comment by ShinoharaYuri** [comment]
https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh_TW

姓名標示 - 非商業性 - 相同方式分享 4.0 國際 (CC BY-NC-SA 4.0)
