### ISSUE TITLE
Remove spaces before <!-- more -->

### ISSUE THREAD

**Issue by ShinoharaYuri** [MOxFIVE/hexo-theme-yelee#99]
https://inoriheart.github.io/Neptune/Update/

```
## 5 月 18 日 (水)

 - 超次元ゲイム ネプテューヌ B2 W スエードタペストリー 今日も元気にねぷねぷ！Ver.

 <!-- more -->
```
測試了一下 是在 上面就會這樣

**Comment by MOxFIVE** [comment]
去掉 `<!-- more -->` 前面的空格后顯示正常
![snip20160518_1](https://cloud.githubusercontent.com/assets/10032927/15357107/6000b9c0-1d2f-11e6-80cc-3ec6fbe3c641.png)
